export const FETCH_POSTS = "FETCH_POSTS";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const FETCH_POSTS_BY_TAG = "FETCH_POSTS_BY_TAG";

export const FETCH_TAGS = "FETCH_TAGS";
export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";

export const FETCH_COMMENTS_BY_SLUG = "FETCH_COMMENTS_BY_SLUG";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const LIKE_ARTICLE = "LIKE_ARTICLE";
export const UNLIKE_ARTICLE = "UNLIKE_ARTICLE";
export const GET_PROFILE = "GET_PROFILE";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const GET_ARTICLES_BY_AUTHOR = "GET_ARTICLES_BY_AUTHOR";

export const GET_ARTICLES_BY_FAVORITED = "GET_ARTICLES_BY_FAVORITED";
export const GET_FOLLOW_FEED = "GET_FOLLOW_FEED";

